--- CREATE PROFILE
Create profile Student limit
SESSIONS_PER_USER UNLIMITED
CPU_PER_SESSION UNLIMITED
CONNECT_TIME 50 
FAILED_LOGIN_ATTEMPTS 2
PASSWORD_LIFE_TIME 30;

--- CREATE USER
CREATE USER DB_CUSTOMER
IDENTIFIED BY Database2021
PROFILE Student
ACCOUNT UNLOCK;

--- CREATE ROLE
CREATE ROLE READ_DB201;

--- GRANT ACCESS TO ROLE
GRANT SELECT ON ALUMNI TO READ_DB201;
GRANT SELECT ON ALUMNI_COURSE TO READ_DB201;
GRANT SELECT ON COURSE_CATALOG TO READ_DB201;
GRANT SELECT ON CURRENT_STUDENTS TO READ_DB201;
GRANT SELECT ON DEGREE TO READ_DB201;
GRANT SELECT ON MARKETPLACE_PRODUCTS TO READ_DB201;
GRANT SELECT ON PICKUP TO READ_DB201;
GRANT SELECT ON PRICE TO READ_DB201;
GRANT SELECT ON PRODUCT TO READ_DB201;
GRANT SELECT ON PROFESSOR TO READ_DB201;
GRANT SELECT ON SHOP TO READ_DB201;
Grant ALTER ANY PROCEDURE to READ_DB201;
GRANT EXECUTE ANY PROCEDURE to READ_DB201;
Grant select on vw_compare to READ_DB201;
Grant select on vw_dmdd to READ_DB201;
Grant select on vw_gpa to READ_DB201;
Grant select on vw_role to READ_DB201;
Grant select on vw_jobtitle to READ_DB201;

--- GRANT ROLE TO USER 
GRANT READ_DB201 TO DB_CUSTOMER;

--- CREATE ROLE
CREATE ROLE DML_DB201;

--- GRANT ACCESS TO ROLE
GRANT INSERT, UPDATE ON MARKETPLACE_PRODUCTS TO DML_DB201;
GRANT INSERT, UPDATE ON PICKUP TO DML_DB201;

--- GRANT ROLE TO USER 
GRANT DML_DB201 TO DB_CUSTOMER;

--- GRANT CREATE SESSION TO USER
GRANT CREATE SESSION TO DB_CUSTOMER;